# Copyright (c) 2017 by Niklaus Giger niklaus.giger@member.fsf.org
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http:#www.eclipse.org/legal/epl-v10.html
#
# This is a setup for running peter schönbuchers privates wiki
#
version: '2.0'
services:
  peter:
    build: .
    networks:
      private:
      public:
    ports:
      - 60080:80
    volumes:
      - $PWD/apache2/common.conf:/etc/apache2/sites-available/000-default.conf
#      - $PWD/pmwiki-2.2.70:/home/web/shared_wiki # Gab Fehler, aber startet auf
      - $PWD/pmwiki-2.2.102:/home/web/shared_wiki
      - /home/web/hosts/peter.schoenbucher.ch/htdocs:/home/web/host/htdocs
      - $PWD/peter.schoenbucher.ch/index.php:/home/web/host/htdocs/index.php
      - $PWD/peter.schoenbucher.ch/skins/peter:/home/web/shared_wiki/pub/skins/peter
      - $PWD/peter.schoenbucher.ch/local:/home/web/host/htdocs/pmwiki/local

  testpeter:
    build: .
    networks:
      private:
      public:
    ports:
      - 61080:80
    volumes:
      - $PWD/apache2/common.conf:/etc/apache2/sites-available/000-default.conf
      - $PWD/pmwiki-2.2.102:/home/web/shared_wiki
      - /home/web/hosts/peter.schoenbucher.ch/htdocs:/home/web/host/htdocs
      - $PWD/peter.schoenbucher.ch/index.php:/home/web/host/htdocs/pmwiki/index.php
      - $PWD/peter.schoenbucher.ch/skins/peter:/home/web/shared_wiki/pub/skins/peter
      - $PWD/peter.schoenbucher.ch/local:/home/web/host/htdocs/pmwiki/local

  iatrix:
    build: .
    networks:
      private:
      public:
    ports:
      - 62080:80
    volumes:
      - $PWD/apache2/common.conf:/etc/apache2/sites-available/000-default.conf
      - $PWD/pmwiki-2.2.102:/home/web/shared_wiki
      - /home/web/hosts/www.iatrix.org/htdocs:/home/web/host/htdocs  
      - $PWD/iatrix.org/index.php:/home/web/host/htdocs/index.php
      - $PWD/skins/peter:/home/web/hosts/www.iatrix.org/htdocs/pub/skins/pmwiki
      - $PWD/iatrix.org/local:/home/web/host/htdocs/local

  praxis:
    build: .
    networks:
      private:
      public:
    ports:
      - 63080:80
    volumes:
      - $PWD/apache2/common.conf:/etc/apache2/sites-available/000-default.conf
      - $PWD/pmwiki-2.2.102:/home/web/shared_wiki
      - /home/web/hosts/praxis.praxisunion.ch/htdocs:/home/web/host/htdocs  
      - $PWD/praxis.praxisunion.ch/index.html:/home/web/host/htdocs/index.html
      - $PWD/praxis.praxisunion.ch/index.php:/home/web/host/htdocs/index.php
      - $PWD/praxis.praxisunion.ch/wk/index.php:/home/web/host/htdocs/wk/pmwiki.php
      - $PWD/praxis.praxisunion.ch/wk/index.php:/home/web/host/htdocs/wk/index.php
      - $PWD/skins/peter:/home/web/hosts/praxis.praxisunion.ch/htdocs/pub/skins/pmwiki
      - $PWD/praxis.praxisunion.ch/local:/home/web/hosts/praxis.praxisunion.ch/htdocs/pmwiki/local

  www_praxis:
    build: .
    networks:
      private:
      public:
    ports:
      - 64080:80
    volumes:
      - $PWD/apache2/common.conf:/etc/apache2/sites-available/000-default.conf
      - $PWD/pmwiki-2.2.102:/home/web/shared_wiki
      - /home/web/hosts/www.praxis.praxisunion.ch/htdocs:/home/web/host/htdocs  
      - $PWD/skins/peter:/home/web/hosts/www.praxis.praxisunion.ch/htdocs/pub/skins/pmwiki
      - $PWD/www.praxis.praxisunion.ch/local:/home/web/hosts/www.praxis.praxisunion.ch/htdocs/pmwiki/local

networks:
  public:
  private:
   
