# Copyright (c) 2017 by Niklaus Giger niklaus.giger@member.fsf.org
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http:#www.eclipse.org/legal/epl-v10.html
#
# This is a setup for running peter schönbuchers privates wiki
#
version: '2.0'
services:
  peter_wiki:
    # image: ngiger/peter_wiki
    build: .
    networks:
      private:
      public:
    extra_hosts:
      - "peter.schoenbucher.ch:127.0.0.1"
    ports:
      - 60080:80
#    working_dir: "/home/web/hosts/peter.schoenbucher.ch/htdocs"
#    command: [ "php", "-S", "0.0.0.0:8080" ]
    working_dir: /home/web/host/htdocs
    volumes:
      - $PWD/pmwiki-2.2.70:/home/web/shared_wiki
      - /home/web/hosts/peter.schoenbucher.ch/logs:/home/web/host/logs  
      - /home/web/hosts/peter.schoenbucher.ch/htdocs:/home/web/host/htdocs  
      - $PWD/peter/skins:/home/web/hosts/peter.schoenbucher.ch/htdocs/pub/skins/pmwiki
      - $PWD/peter/local:/home/web/hosts/peter.schoenbucher.ch/htdocs/pmwiki/local
      - $PWD/apache2/common.conf:/etc/apache2/sites-available/000-default.conf
      # - $PWD/peter/apache/peter.schoenbucher.ch.conf:/etc/apache2/sites-enabled/peter.schoenbucher.ch.conf

  testpeter_wiki:
    build: .
    networks:
      private:
      public:
    ports:
      #- 61080:80
      - 61080:61080
      # - 61443:443
    volumes:
      - $PWD/pmwiki-2.2.102:/home/web/shared_wiki
      - /home/web/hosts/peter.schoenbucher.ch/htdocs:/home/web/hosts/peter.schoenbucher.ch/htdocs  
      - $PWD/skins/peter:/home/web/hosts/peter.schoenbucher.ch/htdocs/pub/skins/pmwiki
      - $PWD/local:/home/web/hosts/peter.schoenbucher.ch/htdocs/pmwiki/local
#      - /etc/letsencrypt:/etc/letsencrypt
  iatrix:
    build: .
    networks:
      private:
      public:
    ports:
      - 62080:62080   # for testing on development machines use the IP-address from the log, e.g. "using 172.21.0.2" > http:172.21.0.2
      - 62443:443
    volumes:
      - $PWD/pmwiki-2.2.102:/home/web/shared_wiki
      - /home/web/hosts/www.iatrix.org/htdocs:/home/web/hosts/www.iatrix.org/htdocs  
      - $PWD/skins/peter:/home/web/hosts/www.iatrix.org/htdocs/pub/skins/pmwiki
      - $PWD/local:/home/web/hosts/www.iatrix.org/htdocs/pmwiki/local
#      - /etc/letsencrypt:/etc/letsencrypt

networks:
  public:
  private:
   
