# Copyright (c) 2017 by Niklaus Giger niklaus.giger@member.fsf.org
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http:#www.eclipse.org/legal/epl-v10.html
#
# This is a setup for running peter schönbuchers privates wiki
#
version: '2.0'
services:
  testpeter:
    build: .
    networks:
      private:
      public:
    ports:
      - 61080:80
    volumes:
      - $PWD/apache2/common.conf:/etc/apache2/sites-available/000-default.conf
      - $PWD/pmwiki-2.2.102:/home/web/shared_wiki
      - /home/web/hosts/peter.schoenbucher.ch/htdocs:/home/web/host/htdocs
      - /home/web/hosts/peter.schoenbucher.ch/htdocs/wiki.d:/home/web/host/htdocs/pmwiki/wiki.d
      - $PWD/peter.schoenbucher.ch/index.php:/home/web/host/htdocs/index.php
      - $PWD/peter.schoenbucher.ch/index.php:/home/web/host/htdocs/pmwiki/index.php
      - $PWD/peter.schoenbucher.ch/skins/peter:/home/web/host/htdocs/pmwiki/pub/skins/peter
      - $PWD/peter.schoenbucher.ch/skins/peter:/home/web/host/htdocs/pub/skins/peter
      - $PWD/peter.schoenbucher.ch/local:/home/web/host/htdocs/pmwiki/local
      - $PWD/peter.schoenbucher.ch/local:/home/web/host/htdocs/local

  www_praxis:
    build: .
    networks:
      private:
      public:
    ports:
      - 64080:80
    volumes:
      - $PWD/apache2/common.conf:/etc/apache2/sites-available/000-default.conf
      - $PWD/pmwiki-2.2.102:/home/web/shared_wiki
      - /home/web/hosts/www.praxis.praxisunion.ch/htdocs:/home/web/host/htdocs  
      - $PWD/skins/peter:/home/web/hosts/www.praxis.praxisunion.ch/htdocs/pub/skins/pmwiki
      - $PWD/www.praxis.praxisunion.ch/local:/home/web/hosts/www.praxis.praxisunion.ch/htdocs/pmwiki/local

networks:
  public:
  private:
   
