# Copyright (c) 2017 by Niklaus Giger niklaus.giger@member.fsf.org
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http:#www.eclipse.org/legal/epl-v10.html
#
# This is a setup for running peter schönbuchers privates wiki
#
version: '2.0'
services:
  peter_wiki:
    # image: ngiger/peter_wiki
    build: .
    networks:
      private:
      public:
    ports:
      - 6543:80
    volumes:
      - /opt/src/peter-wiki-docker/htdocs:/home/web/hosts/peter.schoenbucher.ch/htdocs
      - /opt/src/peter-wiki-docker/shared_wiki/pub/skins/peter:/home/web/hosts/peter.schoenbucher.ch/htdocs/pub/skins/pmwiki
      - /opt/src/peter-wiki-docker/shared_wiki:/home/web/shared_wiki

  testpeter_wiki:
    build: .
    networks:
      private:
      public:
    ports:
      - 6544:80
    volumes:
      - $PWD/pmwiki-2.2.102:/home/web/pmwiki-2.2.102
      - /home/web/hosts/peter.schoenbucher.ch/htdocs:/home/web/hosts/peter.schoenbucher.ch/htdocs  
      - $PWD/skins/peter:/home/web/hosts/peter.schoenbucher.ch/htdocs/pub/skins/pmwiki
      - $PWD/local:/home/web/hosts/peter.schoenbucher.ch/htdocs/pmwiki/local

networks:
  public:
  private:
   
