# Copyright (c) 2017 by Niklaus Giger niklaus.giger@member.fsf.org
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http:#www.eclipse.org/legal/epl-v10.html
#
# This is a setup for running peter schönbuchers privates wiki
#
version: '2.0'
services:
  peter_wiki:
    # image: ngiger/peter_wiki
    build: .
    networks:
      private:
      public:
    ports:
      - 6543:80
#      - 80:80 # dann geht nextcloud nicht mehr!
    volumes:
      # - /opt/src/peter-wiki-docker/htdocs:/var/www # fuer phpinfo.php
      - /opt/src/peter-wiki-docker/htdocs:/home/web/hosts/peter.schoenbucher.ch/htdocs
      - /opt/src/peter-wiki-docker/pmwiki-2.2.70:/home/web/pmwiki-2.2.70
      - $PWD/shared_wiki/pub/skins/peter:/home/web/hosts/peter.schoenbucher.ch/htdocs/pub/skins/pmwiki # dann gibt es gelben Hintergund, aber pmwiki-32.gif wird nicht gefunden
      # - /opt/src/peter-wiki-docker/htdocs/pub:/home/web/shared_wiki/pub -> Dann motzt pmwiki-2.2.70/scripts/skins.php
      - /opt/src/peter-wiki-docker/shared_wiki:/home/web/shared_wiki
        # - ${PWD}/htdocs/:/home/web/hosts/peter.schoenbucher.ch
      # - /home/web/pmwiki-2.2.70.old/:/home/web/pmwiki-2.2.70
      # - /opt/src/peter-wiki-docker/htdocs:/var/www

networks:
  public:
  private:
   
